#!/bin/bash

echo "🚀 AI Buzz World - GitHub Setup Script"
echo "======================================"
echo ""
echo "STEP 1: Create GitHub Repository"
echo "--------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: ai-buzz-world"
echo "3. Description: AI tools directory with clean ad integration"
echo "4. Set to Public or Private (your choice)"
echo "5. DON'T check 'Add a README file' (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "STEP 2: After creating the repository, run these commands:"
echo "--------------------------------------------------------"
echo ""
echo "Replace 'YOUR_USERNAME' with your actual GitHub username:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/ai-buzz-world.git"
echo "git push -u origin main"
echo ""
echo "Example if your username is 'johndoe':"
echo "git remote add origin https://github.com/johndoe/ai-buzz-world.git"
echo "git push -u origin main"
echo ""
echo "🎉 That's it! Your project will be on GitHub!"
echo ""
echo "Current Git Status:"
echo "==================="
git status
echo ""
echo "Your email is configured as: $(git config user.email)"
echo "Your name is configured as: $(git config user.name)"
